### ISSUE TITLE
Consider Packaging

### ISSUE THREAD

**Issue by poppabear8883** [mdbootstrap/mdb-vue-ui-kit#1]
Any chance this will be migrated into a package ? 

As in be able to include a collection of Vue components that use `mdboostrap` as a dependency enabling us to stay up to date on the latest components ?

Right now you are advertising this as a `UI Kit` but, really its just a `vue template with prebuilt mdboostrap Vue components`. This doesn't help us if we just want to utilize the components in our own `Vue Template`

I would suggest to pull out all of the `UI Components` and `mixins` etc ... (basically everything outside of the vue template) and package that up into something like `mdboostrap-vue`.

Then in this template, you simply add that `mdbootstrap-vue` to your dependencies.

This will allow users to either use your template (which can still get package updates) or use their preferred `template` and can simply `npm install mdboostrap-vue --save`. Which would also install all the dependencies that is needed for that package (`mdboostrap`, `boostrap-4.0`, etc ...)

**Comment by poppabear8883** [comment]
I mean think about it, if you add a new component, how are we to update our project to include the new components? Are we expected to just keep coming back and download the files, copy and paste over all the code we "think" has been updated ?

**Comment by smolenski-mikolaj** [comment]
Thanks for advice. Vue version of MDB is still developing and we'll think about migrating into a package.

**Comment by z1haze** [comment]
I 100% agree with this. If the maintainable components of this template were in an npm package that could be updated I would be using it now. I think if you could extract everything but the application code to an npm package, and just have your vue-cli project depend on your package, it would be much more useful. Hopefully you could actually get that done quickly, so we could use it.

**Comment by oleteacher** [comment]
I have to agree with @poppabear8883 We would like to use in some classroom projects but just too hard to add components later.

Nevertheless we are thankful for your project, great teaching tool:)

**Comment by Tinostarn** [comment]
I'm just agree with this suggestion which is like a requirement in modern development
MDB is such a complete tool, looking forward to get a full VueJS integration :)

**Comment by mathroc** [comment]
I tried to add this package using yarn and making the documentation work, here is what I needed to do:

`yarn add https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design`

`cp node_modules/vu-dev/src src/mdb -r`

in src/mdb: `for i in $(git grep -l @/); do sed -i 's/@\//mdb\//' $i; done`

in build/webpack.dev.conf.js, add:

```js
    alias: {
      mdb: path.resolve(__dirname, './../src/mdb'),
    }
```

in your router:

```js
import Vue from "vue";
import Router from "vue-router";
import HelloWorld from "@/components/HelloWorld";
import HomePage from "@/components/HomePage";
import HomePage from "mdb/docs/HomePage";
import GridPage from "mdb/docs/GridPage";
import BadgePage from "mdb/docs/BadgePage";
import CardPage from "mdb/docs/CardPage";
import ButtonPage from "mdb/docs/ButtonPage";
import TablePage from "mdb/docs/TablePage";
import DropdownPage from "mdb/docs/DropdownPage";
import JumbotronPage from "mdb/docs/JumbotronPage";
import CarouselPage from "mdb/docs/CarouselPage";
import BreadcrumbPage from "mdb/docs/BreadcrumbPage";
import FaPage from "mdb/docs/FaPage";
import InputsPage from "mdb/docs/InputsPage";
import LiveDemoPage from "mdb/docs/LiveDemoPage";
import MediaPage from "mdb/docs/MediaPage";
import ListGroupPage from "mdb/docs/ListGroupPage";
import NavbarPage from "mdb/docs/NavbarPage";
import CollapsePage from "mdb/docs/CollapsePage";
import PaginationPage from "mdb/docs/PaginationPage";
import PanelPage from "mdb/docs/PanelPage";
import ChartPage from "mdb/docs/ChartPage";
import ProgressBarsPage from "mdb/docs/ProgressBarsPage";
import TooltipPage from "mdb/docs/TooltipPage";
import PopoverPage from "mdb/docs/PopoverPage";
import EdgeHeaderPage from "mdb/docs/EdgeHeaderPage";
import MasksPage from "mdb/docs/MasksPage";

Vue.use(Router);

const routes = [
	{
		path: "/",
		name: "HomePage",
		component: HomePage,
	},
	{
		path: "/vue-help", // @todo
		name: "HelloWorld",
		component: HelloWorld,
	},
];

routes.push(...mdbDocRoutes);

export default new Router({
	mode: "history",
	routes: [
	{
		path: "/",
		name: "HelloWorld",
		component: HelloWorld,
	},
	{
		path: "/mdb-doc",
		name: "mdbHome",
		component: HomePage,
	}, {
		path: "/mdb-doc/components/badge",
		name: "mdbBadgePage",
		component: BadgePage,
	}, {
		path: "/mdb-doc/components/grid",
		name: "mdbGridPage",
		component: GridPage,
	}, {
		path: "/mdb-doc/components/card",
		name: "mdbCardPage",
		component: CardPage,
	}, {
		path: "/mdb-doc/components/button",
		name: "mdbButtonPage",
		component: ButtonPage,
	}, {
		path: "/mdb-doc/components/table",
		name: "mdbTablePage",
		component: TablePage,
	}, {
		path: "/mdb-doc/components/dropdown",
		name: "mdbDropdownPage",
		component: DropdownPage,
	}, {
		path: "/mdb-doc/components/jumbotron",
		name: "mdbJumbotronPage",
		component: JumbotronPage,
	}, {
		path: "/mdb-doc/components/carousel",
		name: "mdbCarouselPage",
		component: CarouselPage,
	}, {
		path: "/mdb-doc/components/breadcrumb",
		name: "mdbBreadcrumbPage",
		component: BreadcrumbPage,
	}, {
		path: "/mdb-doc/components/icons",
		name: "mdbFaPage",
		component: FaPage,
	}, {
		path: "/mdb-doc/components/inputs",
		name: "mdbInputsPage",
		component: InputsPage,
	}, {
		path: "/mdb-doc/components/liveDemo",
		name: "mdbLiveDemoPage",
		component: LiveDemoPage,
	}, {
		path: "/mdb-doc/components/media",
		name: "mdbMediaPage",
		component: MediaPage,
	}, {
		path: "/mdb-doc/components/listgroup",
		name: "mdbListGroupPage",
		component: ListGroupPage,
	}, {
		path: "/mdb-doc/components/navbar",
		name: "mdbNavbarPage",
		component: NavbarPage,
	}, {
		path: "/mdb-doc/components/collapse",
		name: "mdbCollapsePage",
		component: CollapsePage,
	}, {
		path: "/mdb-doc/components/pagination",
		name: "mdbPaginationPage",
		component: PaginationPage,
	}, {
		path: "/mdb-doc/components/panel",
		name: "mdbPanelPage",
		component: PanelPage,
	}, {
		path: "/mdb-doc/components/chart",
		name: "mdbChartPage",
		component: ChartPage,
	}, {
		path: "/mdb-doc/components/progress-bars",
		name: "mdbProgressBarsPage",
		component: ProgressBarsPage,
	}, {
		path: "/mdb-doc/components/tooltip",
		name: "mdbTooltipPage",
		component: TooltipPage,
	}, {
		path: "/mdb-doc/components/popover",
		name: "mdbPopoverPage",
		component: PopoverPage,
	}, {
		path: "/mdb-doc/components/edge-header",
		name: "mdbEdgeHeaderPage",
		component: EdgeHeaderPage,
	}, {
		path: "/mdb-doc/components/masks",
		name: "mdbMasksPage",
		component: MasksPage,
	},
],
});
```

and using `<router-link>` in docs/HomePage.vue:

```html

      <li><router-link :to="{name: 'mdbBadgePage'}">Badge</router-link></li>
      <li><router-link :to="{name: 'mdbBreadcrumbPage'}">Breadcrumb</router-link></li>
      <li><router-link :to="{name: 'mdbButtonPage'}">Button</router-link></li>
      <li><router-link :to="{name: 'mdbCardPage'}">Card</router-link></li>
      <li><router-link :to="{name: 'mdbCarouselPage'}">Carousel</router-link></li>
      <li><router-link :to="{name: 'mdbDropdownPage'}">Dropdown</router-link></li>
      <li><router-link :to="{name: 'mdbGridPage'}">Grid</router-link></li>
      <li><router-link :to="{name: 'mdbFaPage'}">Icons</router-link></li>
      <li><router-link :to="{name: 'mdbInputsPage'}">Inputs</router-link></li>
      <li><router-link :to="{name: 'mdbJumbotronPage'}">Jumbotron</router-link></li>
      <li><router-link :to="{name: 'mdbListGroupPage'}">List group</router-link></li>
      <li><router-link :to="{name: 'mdbLiveDemoPage'}">Live Demo</router-link></li>
      <li><router-link :to="{name: 'mdbMediaPage'}">Media</router-link></li>
      <li><router-link :to="{name: 'mdbNavbarPage'}">Navbar</router-link></li>
      <li><router-link :to="{name: 'mdbPaginationPage'}">Pagination</router-link></li>
      <li><router-link :to="{name: 'mdbPanelPage'}">Panel</router-link></li>
      <li><router-link :to="{name: 'mdbPopoverPage'}">Popover</router-link></li>
      <li><router-link :to="{name: 'mdbTablePage'}">Table</router-link></li>
      <li><router-link :to="{name: 'mdbTooltipPage'}">Tooltip</router-link></li>
      <li><router-link :to="{name: 'mdbWavesPage'}">Waves</router-link></li>
```

and with this it’s working !

For having a first version really easy to use I think you would only need to:

* pickup a package name (for package.json)
* use relative imports instead of `@/`

once that done, we could already install it using npm or yarn as a git project :)

and for also be able to include the documentation in our project I would recommend you to :

* use `<router-link>` in docs/HomePage.vue
* exports the routes ( maybe in src/router/routes.js so that we could include them in our router easily)

**Comment by poppabear8883** [comment]
@smolenski-mikolaj can we get any response to what we can expect ? Is this something we should follow closely or is it not on your roadmap ?

Thanks in advance

**Comment by smolenski-mikolaj** [comment]
At first, thank You all for Your work and advice. We'll try to prepare a Vue package as soon as possible, but I can't write now the exact update time. Please be patient.

**Comment by smolenski-mikolaj** [comment]
Hi there,

I have good news for You. We've just prepared a npm package of our MDB Vue. You can find it here: https://www.npmjs.com/package/mdbvue.

Just after You add it to Your existing project, You will need to import two files into Your src/main.js file:
```
import 'mdbvue/build/css/mdb.css'
import 'mdbvue/src/components/Waves.css'
```
After it You can import all our components from 'mdbvue', i.e.:
`import { Container, Row, Column, Btn, Card, CardBody, CardHeader, CardImg } from 'mdbvue';`

**Comment by z1haze** [comment]
good work!

**Comment by ddosdor** [comment]
Hi,

unfortunately, not all components are available :( eg MdInput, NavbarNav. You forgot about them in the 'index.js' file

``[Vue warn]: Unknown custom element: <NavbarNav> - did you register the component correctly? ``

**Comment by smolenski-mikolaj** [comment]
Hi,

You're right, these two components are not registered in index.js file. Despite this, You are still able to import them using the following code:

import NavbarNav from 'mdbvue/src/components/NavbarNav';
import MdInput from 'mdbvue/src/components/MdInput';

In the next release it will be fixed, but for this moment the above solution is also giving same results.

**Comment by matejcapco** [comment]
Hi,

I used the package version and the dropdowns are not working. I checked for any event listeners on the dropdown button but there are non.

The code of drop.js from mixins folder is missing from the bundle

**Comment by smolenski-mikolaj** [comment]
Hi,

Did You try to import it like this:
import drop from 'mdbvue/src/mixins/drop'?

**Comment by matejcapco** [comment]
Hi, 
where should I place the import, it should have worked automatically or not?

**Comment by smolenski-mikolaj** [comment]
You should import drop just under components import and then register it as a mixin. 
After it dropdowns should work properly.

**Comment by sorbing** [comment]
I found works solution for used dropdown in navbar..
1. Need register the drop mixin (*only for root app component!*):
```
import mbdVueDropMixin from 'mdbvue/src/mixins/drop';
const app = new Vue({
    el: '#app',
    mixins: [mbdVueDropMixin]
});
```
2. Add the `d-none` class on `dropdown-menu` component (necessarily!):
```
<dropdown tag="li" class="nav-item">
    <dropdown-toggle tag="a" nav-link color="white">Dropdown Menu</dropdown-toggle>
    <dropdown-menu class="d-none">
        <dropdown-item>Action 1</dropdown-item>
    </dropdown-menu>
</dropdown>
```
I hope that I will not face any more similar problems.. Thanks.

**Comment by JStrebeyko** [comment]
Yeah, we hope so to. :) on the side note, the mixin is redundant (it's from the first release of MDB Vue), currently we are using regular components - check it out [here](https://mdbootstrap.com/vue/components/dropdowns/). Cheers!
