### ISSUE TITLE
Click event on button component did not work

### ISSUE THREAD

**Issue by ddosdor** [mdbootstrap/mdb-vue-ui-kit#10]
Hi,

click event in Button component did not work. For the click event, you attach the 'waves' method and it is not possible to handle the standard event for the button. Below is my idea how to solve it.

```
<template>
  <button :is="tag" :class="[className, {'ripple-parent': waves}]" :type="type" :role="role" @click="handleClick">
    <slot></slot>
  </button>
</template>
```

and then in 'methods' property:

```
  methods: {
    handleClick(e) {
      this.wave(e);
      this.$emit('click');
    }
  }
```

This solution will allow to handle an event in the component in a standard way:

```
<Btn size="sm" role="button" @click="myClickMethod">Click!</Btn>
```

**Comment by JStrebeyko** [comment]
Hi there, thanks for letting us know! To listen for a native event for your button in a parent component, please consider using a `.native` <a href="https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components">modfier</a>. That way both waves and your custom event should be OK.

**Comment by ddosdor** [comment]
You're absolutely right. I did not think about it :)
