### ISSUE TITLE
Facing Application error while deploy your package in Heroku

### ISSUE THREAD

**Issue by niti15** [mdbootstrap/mdb-vue-ui-kit#11]
Hi,

When I try to deploy your package to Herkoku, I'm facing the application error. The build has been succeed while Deploy the package. But It throws application error while view the site. 

What is the configuration that I'm missig? Because When I try to run in local, I can see that deafult page.

Can you help me out Plzzz?

**Comment by mattonit** [comment]
do you get any logs?

**Comment by niti15** [comment]
Hi,
Here is my bulid log in Heroku:

-----> Node.js app detected

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_VERBOSE=false

       NODE_ENV=production

       NODE_MODULES_CACHE=true

-----> Installing binaries

       engines.node (package.json):  >= 4.0.0

       engines.npm (package.json):   >= 3.0.0

       

       Resolving node version >= 4.0.0...

       Downloading and installing node 9.8.0...

       Bootstrapping npm >= 3.0.0 (replacing 5.6.0)...

       npm 5.7.1 installed

-----> Restoring cache

       Skipping cache restore (not-found)

-----> Building dependencies

       Installing node modules (package.json + package-lock)

       

       > uglifyjs-webpack-plugin@0.4.6 postinstall /tmp/build_690ac2f17ff2380411c17284a53ecf65/niti15-vue-mb-44723b2/node_modules/uglifyjs-webpack-plugin

       > node lib/post_install.js

       

       

       > bootstrap-vue@1.5.1 postinstall /tmp/build_690ac2f17ff2380411c17284a53ecf65/niti15-vue-mb-44723b2/node_modules/bootstrap-vue

       > opencollective postinstall || exit 0

       

       

       *** Thank you for using bootstrap-vue! ***

       

       Please consider donating to our open collective

       to help us maintain this package.

       

       https://opencollective.com/bootstrap-vue/donate

       

       ***

       

       added 1683 packages from 1313 contributors in 29.235s

-----> Caching build

       Clearing previous node cache

       Saving 2 cacheDirectories (default):

       - node_modules

       - bower_components (nothing to cache)

-----> Pruning devDependencies

       removed 1093 packages in 14.735s

-----> Build succeeded!

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 32.4M

-----> Launching...

       Released v3

       https://cryptic-lowlands-12457.herokuapp.com/ deployed to Heroku

**Comment by niti15** [comment]
@mattonit Do you have solution on this issue?

**Comment by smolenski-mikolaj** [comment]
Hi there,

We're planning to test our MDB Vue in heroku before future updates. Thank You all for letting us know about the issue.

**Comment by Sk4s** [comment]
Hi,

I want to use MDB Vue with Heroku, any news about it ?

**Comment by smolenski-mikolaj** [comment]
We've tested our app with Heroku following this guide:
https://medium.com/netscape/deploying-a-vue-js-2-x-app-to-heroku-in-5-steps-tutorial-a69845ace489

It is working correctly.
