### ISSUE TITLE
Requires SSR integration with NUXTJS

### ISSUE THREAD

**Issue by AGDholo** [mdbootstrap/mdb-vue-ui-kit#13]
NUXT: [nuxtjs.org](https://nuxtjs.org)
Hope will have NUXT-CLI 
Refer to this project: [https://github.com/vuetifyjs/nuxt](https://github.com/vuetifyjs/nuxt)

**Comment by ghost** [comment]
Came here looking for the same thing! I can't just npm install mdbvue into my Nuxt project and run  npm run dev like I normally do.

Has anyone integrated Nuxt.js project with mdbvue and would like to help give me some guidance?

**Comment by ghost** [comment]
Just a note: Vuetifyjs has fast support and has been great to work with so far.
So many things are convenient about it. - And they already have a Nuxt module for it.

**Comment by AGDholo** [comment]
@ChrisDillinger  
Your can try the no-ssr option, I have not worked on the project, just a suggestion.
Reference link:
https://nuxtjs.org/guide/plugins#client-side-only
https://nuxtjs.org/api/components-no-ssr

**Comment by JStrebeyko** [comment]
Obviously SSR is awesome and Nuxt integration is a must. It has been scheduled, so please watch this space for updates!

**Comment by ghost** [comment]
@AGDholo I think it needs to be a Nuxt module still in order to be used.. right?
And it doesn't help if we need the SSR version too - thank you though!

**Comment by lanwilds** [comment]
i use vuetify JS it's more convenient and good option with Nuxt JS

**Comment by JStrebeyko** [comment]
> hold my beer

**Comment by AndrewBogdanovTSS** [comment]
@lanwilds what are you doing in this thread then? Please guys, let's not spam a thread with unrelated stuff. The request is pretty obvious.

**Comment by lanwilds** [comment]
@AndrewBogdanovTSS I'm not spamming sir I'm giving suggestions as this is (GitHub) is a open source platform I can use any name and any application which is open source..

**Comment by dwfee** [comment]
when is nuxt support about to become integrated?

**Comment by JStrebeyko** [comment]
No promises, but we're having a technical review of this feature next week and if it all goes well it should be integrated really soon

**Comment by michaelwills** [comment]
Looks like `mdbvue` would also need a CommonJS build: https://github.com/nuxt/nuxt.js/issues/1896

**Comment by michaelwills** [comment]
Some progress. Short version:

* Taking the `.babelrc` from mdbootstrap/Vue-Bootstrap-with-Material-Design, without the `test` properties
* run `npx babel-upgrade --write --install`
* added `build.babel.babelrc = true` to `nuxt.config.js`
* added a minimal `mdbvue.js` plugin but after experimenting, the only thing remaining there are the css imports

This gets it mostly working except you can't do

```
import { mdbIcon } from 'mdbvue'
```

It needs to be

```
import { mdbIcon } from '../node_modules/mdbvue/src/components/Fa'
```

and they don't work with `nuxt generate` within the `mdbvue.js` plugin. In the case of the icon, if I used

```
import { mdbIcon } from '../node_modules/mdbvue/src/components/Fa'

Vue.component('mdbIcon', mdbIcon)
```
it can compile, but `mdb-icon` is not rendered. It remains `<mdb-icon...` in the generated output. So I can play with it for now. :)

**Comment by JStrebeyko** [comment]
Wow, thanks a ton, @michaelwills! Should be able to have a look into the import issue soon.

**Comment by smolenski-mikolaj** [comment]
Hi there!

I've prepared a quick guide about Nuxt and MDB integration. Please follow it if You want to install our library easily in your Nuxt App.

https://mdbootstrap.com/articles/vue/mdb-vue-nuxt-js-quick-start-guide/
