### ISSUE TITLE
Can't load local image in carousel

### ISSUE THREAD

**Issue by wuzi** [mdbootstrap/mdb-vue-ui-kit#18]
Hey,

I'm trying to load a local image in carousel like this

```
<carousel-item :class="{active: show[0]}" img src="../assets/plane.jpg" mask="black-light" alt="First slide">
    <carousel-caption title="Light mask"></carousel-caption>
</carousel-item>
```

And it doesn't load, but using `<img>` tag with same path in same component loads the image.

**Comment by smolenski-mikolaj** [comment]
If You want to import local image inside the component please follow this steps:

1. Import image to Your page:
import plane from '../assets/plane.jpg';
2. Add it to data objects:
data() {
 return {
  plane_src: plane
 };
}
3. Finally add it to 'carousel-item':
`<carousel-item :class="{active: show[0]}" img :src="plane_src" mask="black-light" alt="First slide">`

**Comment by wuzi** [comment]
It works!

Thank you.

**Comment by AMPZart** [comment]
Can you show code please?
