### ISSUE TITLE
Too tiny on phones

### ISSUE THREAD

**Issue by IAntonioDev** [mdbootstrap/mdb-vue-ui-kit#19]
On phones is really tiny, all the components. it's just a fresh installation
![sin titulo](https://user-images.githubusercontent.com/16474660/43597475-776ab59c-9682-11e8-9517-5743dcdd52c9.png)

I tried it on a phone and is also like that. You can't read the text.

**Comment by smolenski-mikolaj** [comment]
Thank for Your remarks. We'll check it and fix it with one of the next releases.
