### ISSUE TITLE
No NavbarItemDropdown Component

### ISSUE THREAD

**Issue by poppabear8883** [mdbootstrap/mdb-vue-ui-kit#2]
As stated in the docs there should clearly be a `NavbarItemDropdown` Component.

```html
<navbar class="indigo" name="Navbar" href="#"> 
  <navbar-collapse> 
    <navbar-nav> 
      <navbar-item href="#" :active="true">Home</navbar-item> 
      <navbar-item href="#">Features</navbar-item> 
      <navbar-item href="#">Pricing</navbar-item> 
      <navbar-item-dropdown label="Dropdown"> 
        <a class="dropdown-item" href="#">Action</a> 
        <a class="dropdown-item" href="#">Another action</a> 
        <a class="dropdown-item" href="#">Something else here</a> 
      </navbar-item-dropdown> 
    </navbar-nav> 
    <form class="form-inline"> 
      <input class="form-control mr-auto p-2" type="text" placeholder="Search" aria-label="Search"> 
    </form> 
  </navbar-collapse> 
</navbar>
```

`Official stable release` NOR `master` contains this component.

```
This dependency was not found:

* @/components/NavbarItemDropdown in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue
```

And another good example why its important to package this up properly Referencing Issue #1

**Comment by poppabear8883** [comment]
Looks like `NavbarItemDropdown` is included in the `-alpha` tagged release ??

**Comment by JStrebeyko** [comment]
Hi there @poppabear8883,

Thanks tenfold for noting! Obviously the docs got outdated, got fixed already. In the beta we opted for a more light-weight and flexible solution, which is using the already-existent dropdown for the navbar. Cheers :beers:

**Comment by poppabear8883** [comment]
@JStrebeyko looks like the docs are fixed now. Appreciate the quick response and clarification on the issue.
