### ISSUE TITLE
Wrong usage of :is

### ISSUE THREAD

**Issue by MarienMonnier** [mdbootstrap/mdb-vue-ui-kit#23]
Hello,

In all your components, you are specifying `:is="tag"` which causes some refresh issues with md-input (for example, I didn't test with all components).

For example, I am doing some kind-of todo list : https://codesandbox.io/s/mmyw0rmlvy

With the `:is` attribute, the `newValue = ""` is not respected and the input is not cleared when i click on Add:
![image](https://user-images.githubusercontent.com/8627898/44262997-7bd35980-a21d-11e8-899f-4bce71309315.png)

From what I can tell in the documentation for the `is` attribute: https://vuejs.org/v2/api/#is
It is used when an element name is invalid inside another element. For example, if my custom element is a custom `<tr>`, I can't do that, because it is not valid in HTML:
```
<table>
  <custom-element></custom-element>
</table>
```

So instead, I must do that:
```
<table>
  <tr is="custom-element"></tr>
</table>
```
See also: https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats

Note that this limitation does not apply for single-file vue components.

Is there any reason why you are using `is` here?
Can you remove them so we can use md-input?

Thanks,

**Comment by jpickwell** [comment]
Should probably be using the `component` element.

* https://vuejs.org/v2/guide/components.html#Dynamic-Components
* https://vuejs.org/v2/api/#component

**Comment by anna-morawska** [comment]
Hello,
thank you for reporting this, we will take it into consideration.
