### ISSUE TITLE
Navbar component cannot always find a "collapse" element.

### ISSUE THREAD

**Issue by jpickwell** [mdbootstrap/mdb-vue-ui-kit#24]
In the `Navbar` component's `mounted` method, `this.collapse` is set to `this.$el.children.navbarSupportedContent`. This is too explicit and brittle. What if the `NavbarCollapse` component is not a direct child of the `Navbar`, then `this.collapse` will be `undefined`.

Since ids are meant to be unique on a page, a simple `document.getElementById('navbarSupportedContent')` is much better. The `target` prop already provides a way to specify the collapse id, but it needs to be changed to not require the "`#`" prefix.

**Comment by Rotarepmi** [comment]
Thank you for your fixes proposal. We'll discuss it within our team.
