### ISSUE TITLE
Using without node.js and npm

### ISSUE THREAD

**Issue by yjlin0224** [mdbootstrap/mdb-vue-ui-kit#26]
It is possible to use Vue + Bootstrap without node.js and npm, just include `vue.js`, `bootstrap-vue.js`, `bootstrap.min.css`, `bootstrap-vue.css`, `polyfill.min.js` in a html file (See [bootstrap-vue docs](https://bootstrap-vue.js.org/docs/#browser)). And, `Vue Material` and `Vuetify` (also Material Design theme based on Vue.js) can work without npm.

Is it possible to use `Vue-Bootstrap-with-Material-Design` without node.js and npm?

**Comment by smolenski-mikolaj** [comment]
There is such possibility but we haven't tested it yet. We highly reccomend to use our package with node and npm for this moment.
