### ISSUE TITLE
mdb-input value is not updated if model changes

### ISSUE THREAD

**Issue by thomsa** [mdbootstrap/mdb-vue-ui-kit#27]
Hello there,

`<mdb-input type="text" v-model="someModel.property" />`
If I change the someModel.property programatically the input never updates itself.

Is there a workaround?

Thanks!

**Comment by thomsa** [comment]
Just checked on 4.3.0 with md-input it was working.
In 4.8.x with mdb-input the update doesn't work anymore on model property change.

**Comment by zmqcherish** [comment]
I am experiencing the same problem.

**Comment by smolenski-mikolaj** [comment]
Hi there,

With the latest update (4.10.0) we fixed that issue.
