### ISSUE TITLE
Navbar can not auto close when using in mobile

### ISSUE THREAD

**Issue by zmqcherish** [mdbootstrap/mdb-vue-ui-kit#28]
using navbar in mobile like below image show
when tap the hamburger icon, the navbar menu open, 
then tap the menu(may be the 'css') 
the page navigate the right page, but the navbar menu can not auto close. you should tap the hamburger icon again.

![qq 20181104135423](https://user-images.githubusercontent.com/6880848/47960598-272fc580-e039-11e8-86b5-d159a3d5007f.jpg)

**Comment by JStrebeyko** [comment]
你好,
Big thanks for noticing - because of this it got [fixed](https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/commit/f69c401163c133d7c32e52acd9d4a658950a9473) pretty fast. Rock on, @zmqcherish ! :beers:

**Comment by zmqcherish** [comment]
@JStrebeyko thanks to fix the bug.
But for the fix, there come to another problem:
when there is a dropdown component, and then tap the dropdown toggle to choose a dropdown menu,
the navbar auto close, I want the navbar auto close when a menu is selected.
So, is it a complex logic?

**Comment by JStrebeyko** [comment]
@zmqcherish good one! I think we might need to put some extra love into dropdowns inside the collapsible navbars. Again, perhaps a `.stop` event listener modifier on dropdown could help? We will dedicate attention to it in the upcoming month. Cheers! :beers:

**Comment by zmqcherish** [comment]
@JStrebeyko emmm.. i don't know how to use .stop event to pevent the wrong logic.
And in mdbvue version 4.9.0, it still has the problem, hope you to fix it.
thanks.
