### ISSUE TITLE
Get wrong close logic when use two modal

### ISSUE THREAD

**Issue by zmqcherish** [mdbootstrap/mdb-vue-ui-kit#30]
There are two modal in a template, we call they modalA and modalB, and there are two value visibleA and visibleB to control the two modal visible
when I click a button to set visibleA = true, then the modalA show.
then click another button(in modalA body) to set  visibleB = true, then the modalB show too.
but when I click the blank zone, which is outside the modalB, the two modal are both close.
I want that just modalB close, how to realize it, thanks.

**Comment by JStrebeyko** [comment]
Hi there,

Thanks for reaching out with it! It should be fixed soon, but for anyone struggling with it now, have you considered adding the `.stop` modifier onto modal overlay? I feel it might be just going through.

Cheers,
Kuba

**Comment by smolenski-mikolaj** [comment]
Hi there,

With the latest update (4.10.0) we fixed that issue. You can check the first modal in our demo page inside Vue package.
