### ISSUE TITLE
MDB Vue Pro

### ISSUE THREAD

**Issue by FWScripte** [mdbootstrap/mdb-vue-ui-kit#32]
After buying mdb pro it seems to be an unachievable task to install it.

GitLab account was created, but cant be accessed. "You have to confirm your email address"...  I have not received anythink similar. 
After posting in official mdbootstrap forums it kinda seems like my ip or whatever got banned. ´Cause after klicking "post" i am not able to enter anything on mdbootstrap.com/*... Tried this on 2 machines and 2 ips..

**Comment by mattonit** [comment]
@Jurelus, please contact me at b.malanowski@mdbootstrap.com

**Comment by mattonit** [comment]
Closed due to no response
