### ISSUE TITLE
Typo/bug in Datatable.vue component

### ISSUE THREAD

**Issue by WickedSilver** [mdbootstrap/mdb-vue-ui-kit#38]
The following lines are mentioning (this.)re**ps**onsive instead of responsive.
This will (as far as i saw) lead to the `responsiveMd` and `responsiveSm` options not working. 

https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/blob/73b25a8efcc8298edd473e3f188bd8c32d34fe53/src/components/Datatable.vue#L320

https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/blob/73b25a8efcc8298edd473e3f188bd8c32d34fe53/src/components/Datatable.vue#L321

Hope this is the right place for this issue and hope it helps.

**Comment by mdembna** [comment]
Hi,
Thank you for letting us know! I've already fixed it and this change will be included in the next release. Kind regards,
Magdalena
