### ISSUE TITLE
Adding to existing project does not work

### ISSUE THREAD

**Issue by monkiki** [mdbootstrap/mdb-vue-ui-kit#39]
I've followed the Vue 5 min quick start at https://mdbootstrap.com/docs/vue/getting-started/quick-start/ and I was no able to add to an existing Vue project. Followed the steps but after adding a "mdb-btn" it does not render properly.

Thanks in advance.

**Comment by mdembna** [comment]
Hi,
As I understand your app doesn't crush, so I suspect that a component might not be registered correctly - make sure that you import and list it in components as shown below: 
```
<template>
    <mdb-btn>Hello world</mdb-btn>
</template>

<script>
import { mdbBtn } from 'mdbvue';
export default {
  components: {
    mdbBtn
  },
}
</script>
```
If your component still doesn't render as it should, please share your code. 
Kind regards,
Magdalena

**Comment by monkiki** [comment]
When I include the <script> part, this error is shown:

Error: Cannot find module 'postcss-import'

I've uploaded the sample proyecto to GitHub and you can see the changes in this pull request https://github.com/monkiki/mdbootstrap-test/pull/1

**Comment by mdembna** [comment]
Please run following command if you're using yarn: `yarn add postcss-import` or `npm install postcss-import` . It should solve your problem. I apologize for the inconvenience.
Kind regards

**Comment by monkiki** [comment]
Great! Please, update documentation because more people should have the same issue.

Thanks a lot!

**Comment by monkiki** [comment]
It really should be:
```
npm install --save postcss-import
```
Now it really works.
