### ISSUE TITLE
I can't install the dependency into Vue.js

### ISSUE THREAD

**Issue by KaitoXion** [mdbootstrap/mdb-vue-ui-kit#41]
Although the dependancy is said to be installed on the web console/ dependencies section, 
the file cannot be found in Node_Modules of Vue.js (am using Visual Studio Code)

thus, I can't do the importing or anything, e.g. : this code section.

```
import { animateOnScroll } from "mdbvue";

  export default {
    name: "AnimationsPage",
    directives: {
      animateOnScroll
    }
  }
```
since I can't do the importing, due to **mdbvue** cannot be found. then that's mean there is a problem.

will be great if I can receive some guidance, am a newbie.

**Comment by smolenski-mikolaj** [comment]
As I checked in the following file https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/blob/master/src/index.js the import of animateOnScroll is included. I just tested it and it works fine. Do You use the latest version of package? It's a new directive, which is not included in the older versions of MDB Vue.

**Comment by KaitoXion** [comment]
Yes. is my way of importing it wrong? cause this way of importing is actually shown on the documentation. 
https://mdbootstrap.com/docs/vue/css/animations/

I haven't try to import it on the "component level?" or only this specific function;
`import animateOnScroll from './directives/AnimateOnScroll';`

**Comment by smolenski-mikolaj** [comment]
Hi, please import the animations directive in the same way as any other component (on the component level). It will work as shown in our docs.

**Comment by KaitoXion** [comment]
> please import the animations directive in the same way as any other component (on the component level). It will work as shown in our docs.

I see, I understand. thank you very much for the information. :)
