### ISSUE TITLE
Why is filterArray undefined 

### ISSUE THREAD

**Issue by awalthefirst** [mdbootstrap/mdb-vue-ui-kit#44]
https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/blob/2db649f22b7248bb082405ef99d1e287c3ae1335/src/components/Tables/Datatable.vue#L507

Hello, I am gettting the following error -> [Vue warn]: Error in callback for watcher "rows": "TypeError: this.filterArray is not a function"

It seems that filterArray isn't defined anywhere

**Comment by mdembna** [comment]
This issue is already resolved and will be fixed in the upcoming release (5.8.0).
