### ISSUE TITLE
Custom column label from Other JSON structures

### ISSUE THREAD

**Issue by DearPureone** [mdbootstrap/mdb-vue-ui-kit#45]
from this example with Other JSON structures

> mounted(){
  fetch('https://jsonplaceholder.typicode.com/todos')
    .then(res => res.json())
    .then(json => {
      let keys = ["id", "title", "completed"];
      let entries = this.filterData(json, keys);
      //columns
      this.columns = keys.map(key => {
        return {
          label: key.toUpperCase(),
          field: key,
          sort: 'asc'
        };
      });
      //rows
      entries.map(entry => this.rows.push(entry));
    })
    .catch(err => console.log(err));
}

is it possible to custom label of column like

> columns: [
        {
          label: 'Name',
          field: 'name',
          sort: 'asc'
        },
        {
          label: 'Position',
          field: 'position',
          sort: 'asc'
        },

I’m looking forward to your reply.

**Comment by mdembna** [comment]
As I understand, you wish to hardcode columns with custom labels in your data object and then fetch data from database and create rows array based on that? Custom labels aren't a problem as long as the field value corresponds to the given key row object. So If you have columns:

**Comment by mdembna** [comment]
As I understand, you wish to hardcode columns with custom labels in your data object and then fetch data from database and create rows array based on that? Custom labels aren't a problem as long as the field value corresponds to the given key in the row object:
```
columns: [
{
label: 'Custom name',
field: 'name',
sort: 'asc'
},
{
label: 'Some other field',
field: 'position',
sort: 'asc'
},
rows: [
{ name: "Value", position: "Value" }
]
```
