### ISSUE TITLE
touch directive is not found

### ISSUE THREAD

**Issue by achimoraites** [mdbootstrap/mdb-vue-ui-kit#47]
In [Carousel API ](https://mdbootstrap.com/docs/vue/advanced/carousel/#docsTabsOverview )
in api reference the  **touch** directive is used to add mobile touch events to carousel.
But when i try to use it
`  <mdb-multi-carousel slide>` this results in 
`[Vue warn]: Failed to resolve directive: touch`

**Comment by mdembna** [comment]
Which installation method did you use? 
To use touch events those two lines must be included in `main.js` - open the mdbvue folder in node modules and check if you have those. If not, try adding them to your project. Let me know about the installation method, it would be easier for us to find a bug. 
```
Vue.use(Vue2TouchEvents);
import Vue2TouchEvents from 'vue2-touch-events';
```
