### ISSUE TITLE
Carousel does not change control icons

### ISSUE THREAD

**Issue by almidi** [mdbootstrap/mdb-vue-ui-kit#49]
The carousel component's leftIcon and rightIcon properties do not apply when the carousel is not in multi-item mode.

my code:

`    <mdb-carousel
      :items="banners"
      :interval="5000"
      slide
      touch
      controlls
      leftIcon="paper-plane"
      rightIcon="paper-plane"
    >
    </mdb-carousel>`

**Comment by smolenski-mikolaj** [comment]
That feature was just released. There is now option to use **controllIcons** property. Example:

`<mdb-carousel :items="3" :controllIcons="['fas fa-arrow-circle-left fa-2x text-white', 'fas fa-arrow-circle-right fa-2x text-white']">`

Best regards
