### ISSUE TITLE
[Bug] npm package missing source map

### ISSUE THREAD

**Issue by Chaostheorie** [mdbootstrap/mdb-vue-ui-kit#53]
I've recently started working with the npm version of mdb-vue (free). When trying to embed into an app I couldn't get it to work. After some debugging it seems like the `mdbvue.umd.min.js.map` is missing from the npm package. Contradictory it's provided by the featured/ recommended CDNs such as [cdn.jsdelivr.net](https://cdn.jsdelivr.net/npm/mdbvue/lib/mdbvue.umd.min.js.map).

The file seems also not to be defined in the [/lib](https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/tree/master/lib) folder of this repository. 

Have I missed some building step? I added the `mdb` package with `vue add mdb`. Help is really appreciated. Thanks in advance

**Comment by smolenski-mikolaj** [comment]
Source map for js will be added with the next release (26.07). 

Keep coding, 
Mikołaj from MDB

**Comment by Chaostheorie** [comment]
Thank you for the update
