### ISSUE TITLE
missing scss alerts?

### ISSUE THREAD

**Issue by migliori** [mdbootstrap/mdb-vue-ui-kit#54]
Hi,

I'm using MDBVue with SCSS

Am I wrong or is the _alert.scss missing in the _lib/scss/free/_ folder?

`<mdb-alert color="info">alert content</mdb-alert>`

My alerts are using the default _bootstrap-css-only_ colors instead of the MDB core color variables.

**Comment by smolenski-mikolaj** [comment]
Hi there,

There is no additional scss for alerts. All you need is to add mdb colors scss file to overwrite the default variables.

Keep coding, 
Mikołaj from MDB
