### ISSUE TITLE
The color-adjust shorthand is currently deprecated

### ISSUE THREAD

**Issue by luc122c** [mdbootstrap/mdb-vue-ui-kit#58]
I'm getting a console warning from AutoPrefixer.
`autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.`

It looks like it's currently used [here](https://github.com/mdbootstrap/mdb-vue-ui-kit/blob/2897f3d6bc5d5def1daf424ecb7402d1d27a3865/src/scss/standard/bootstrap-rtl-fix/forms/_form-check.scss#L28) and [here](https://github.com/mdbootstrap/mdb-vue-ui-kit/blob/2897f3d6bc5d5def1daf424ecb7402d1d27a3865/src/scss/standard/bootstrap/forms/_form-check.scss#L28). 

It looks like this is an upstream issue in Bootstrap which should be [fixed soon](https://github.com/twbs/bootstrap/pull/36283#issuecomment-1150129558).

**Comment by smolenski-mikolaj** [comment]
Thanks, we're goint to update Bootstrap version soon and hope that the issue will be fixed.

**Comment by luc122c** [comment]
Hi @smolenski-mikolaj, this has been [fixed upstream in Bootstrap](https://github.com/twbs/bootstrap/pull/36283) for some time. Do you have an ETA for when this will be updated by MDB?

**Comment by smolenski-mikolaj** [comment]
The last fixes are already waiting for the release. Most probably it will happen on January 9.
