### ISSUE TITLE
How to build from SRC to modify .vue components?

### ISSUE THREAD

**Issue by WolfJMZ** [mdbootstrap/mdb-vue-ui-kit#62]
Hi there!

I'm trying to edit the source components myself, but seeing as the package.json doesn't include any build instructions or dependencies required, importing from mdb-vue-ui-kit/src/index.free isn't possible thus modifications to the .vue components aren't possible.

How can I make my own version of mdb-vue that includes features and changes to components I want to see?

Additionally, trying to compile in typescript for a build results in errors in the following files (when importing from src/index.free):
```
     4  ......src/components/free/components/MDBAccordionItem.vue:73
     1  ......src/components/free/components/MDBBtn.vue:21
     2  ......src/components/free/components/MDBCard.vue:14
     2  ......src/components/free/components/MDBCardBody.vue:14
    11  ......src/components/free/components/MDBCarousel.vue:66
    20  ......src/components/free/components/MDBCollapse.vue:3
    11  ......src/components/free/components/MDBDropdown.vue:21
     2  ......src/components/free/components/MDBDropdownItem.vue:2
    14  ......src/components/free/components/MDBDropdownMenu.vue:57
     2  ......src/components/free/components/MDBDropdownToggle.vue:72
     5  ......src/components/free/components/MDBModal.vue:3
    13  ......src/components/free/components/MDBPopover.vue:45
     4  ......src/components/free/components/MDBTooltip.vue:38
     1  ......src/components/free/forms/MDBFile.vue:27
    15  ......src/components/free/forms/MDBInput.vue:234
     5  ......src/components/free/forms/MDBTextarea.vue:215
     2  ......src/components/free/layout/MDBRow.vue:14
     2  ......src/components/free/navigation/MDBFooter.vue:14
     5  ......src/components/free/navigation/MDBNavbar.vue:114
     1  ......src/components/free/navigation/MDBNavbarItem.vue:26
     4  ......src/components/free/navigation/MDBTabItem.vue:54
     1  ......src/components/free/navigation/MDBTabNav.vue:44
     7  ......src/components/free/navigation/MDBTabPane.vue:4
    14  ......src/components/free/navigation/MDBTabs.vue:38
```

Thanks in advance!

**Comment by juujisai** [comment]
Hi! I think the best way is to copy the code from the `src` folder (either from this repo or node_modules), make the changes you need and use it like you would with your own components.

As of the typescript errors when copying the code from `src` directory, unfortunately they are caused by a `"strict": false,` option added inside the tsconfig file. We are planning to improve the typescript support for `mdb-vue-ui-kit` for the next release.

Hope that helps!

**Comment by WolfJMZ** [comment]
Is there a way for me to build it myself and regenerate the mdb.umd.min.js and mdb.es.min.js files or exclude the MDB folder from typescript validation altogether in my project without having to set strict:false?

**Comment by juujisai** [comment]
Checkout this topic https://mdbootstrap.com/support/vue/how-to-use-vue-components-instead-of-d-ts-to-make-custom-build-of-mdb-vue-ui-kit-pro-advanced/

At the very bottom there will be some instructions on how to create a custom build
