### ISSUE TITLE
Intregration with other Vue frameworks

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [mdbootstrap/mdb-vue-ui-kit#9]
Hi! I'm impressed with your idea to integrate Vue and Bootstrap. But I also like working with Nuxt and TypeScript. Is there any way to integrate your Bt components into other templates, such as [Nuxt Typescript Starter Template](https://github.com/nuxt-community/typescript-template) ?

**Comment by JStrebeyko** [comment]
Thanks! Yes, there is - check it out here: https://github.com/mdbootstrap/Vue-Bootstrap-with-Material-Design/issues/1#issuecomment-361023009
